export const stadiumPdfUrls = [
  { id: 1, name: "桐生", url: "https://www.kiryu-kyotei.com/pdf/today_race.pdf" },
  { id: 2, name: "戸田", url: "https://www.boatrace-toda.jp/pdf/today_race.pdf" },
  { id: 3, name: "江戸川", url: "https://www.boatrace-edogawa.com/pdf/today_race.pdf" },
  { id: 4, name: "平和島", url: "https://www.heiwajima.gr.jp/pdf/today_race.pdf" },
  { id: 5, name: "多摩川", url: "https://www.boatrace-tamagawa.com/pdf/today_race.pdf" },
  { id: 6, name: "浜名湖", url: "https://www.boatrace-hamanako.jp/pdf/today_race.pdf" },
  { id: 7, name: "蒲郡", url: "https://www.gamagori-kyotei.com/pdf/today_race.pdf" },
  { id: 8, name: "常滑", url: "https://www.boatrace-tokoname.jp/pdf/today_race.pdf" },
  { id: 9, name: "津", url: "https://www.boatrace-tsu.com/pdf/today_race.pdf" },
  { id: 10, name: "三国", url: "https://www.boatrace-mikuni.jp/pdf/today_race.pdf" },
  { id: 11, name: "びわこ", url: "https://www.boatrace-biwako.jp/pdf/today_race.pdf" },
  { id: 12, name: "住之江", url: "https://www.boatrace-suminoe.jp/pdf/today_race.pdf" },
  { id: 13, name: "尼崎", url: "https://www.boatrace-amagasaki.jp/pdf/today_race.pdf" },
  { id: 14, name: "鳴門", url: "http://www.n14.jp/pdf/today_race.pdf" },
  { id: 15, name: "丸亀", url: "https://www.marugameboat.jp/pdf/today_race.pdf" },
  { id: 16, name: "児島", url: "https://www.kojimaboat.jp/pdf/today_race.pdf" },
  { id: 17, name: "宮島", url: "https://www.boatrace-miyajima.com/pdf/today_race.pdf" },
  { id: 18, name: "徳山", url: "https://www.boatrace-tokuyama.jp/pdf/today_race.pdf" },
  { id: 19, name: "下関", url: "https://www.boatrace-shimonoseki.jp/pdf/today_race.pdf" },
  { id: 20, name: "若松", url: "https://www.wmb.jp/pdf/today_race.pdf" },
  { id: 21, name: "芦屋", url: "https://www.boatrace-ashiya.com/pdf/today_race.pdf" },
  { id: 22, name: "福岡", url: "https://www.boatrace-fukuoka.com/pdf/today_race.pdf" },
  { id: 23, name: "唐津", url: "https://www.boatrace-karatsu.jp/pdf/today_race.pdf" },
  { id: 24, name: "大村", url: "https://www.omurakyotei.jp/pdf/today_race.pdf" }
];