// server/venues.js
export const VENUES = [
  { name: "桐生", code: "01" },
  { name: "戸田", code: "02" },
  { name: "江戸川", code: "03" },
  { name: "平和島", code: "04" },
  { name: "多摩川", code: "05" },
  { name: "浜名湖", code: "06" },
  { name: "蒲郡", code: "07" },
  { name: "常滑", code: "08" },
  { name: "津", code: "09" },
  { name: "三国", code: "10" },
  { name: "びわこ", code: "11" },
  { name: "住之江", code: "12" },
  { name: "尼崎", code: "13" },
  { name: "鳴門", code: "14" },
  { name: "丸亀", code: "15" },
  { name: "児島", code: "16" },
  { name: "宮島", code: "17" },
  { name: "徳山", code: "18" },
  { name: "下関", code: "19" },
  { name: "若松", code: "20" },
  { name: "芦屋", code: "21" },
  { name: "福岡", code: "22" },
  { name: "唐津", code: "23" },
  { name: "大村", code: "24" }
];